package common;

public enum TypeOfMessage {
	REQUESTINFO, UPDATEINFO, LOGIN_REQUEST, LOGOUT, NEW_ORDER, GET_INFO,
	TOURGETORDERS, TOURGUIDELOGIN, TOURGUIDEDETAILS, TOURGUIDENEWORDER, CHECKMAXVIS,
	UPDATEINFO_REQUEST, UPDATE_ORDER, DELETE_INFO,TOURGUIDEWAITINGLIST;
	 
}
