package common;

public enum TypeOfMessage {
	REQUESTINFO, UPDATEINFO, LOGIN_REQUEST, LOGOUT, NEW_ORDER, GET_INFO,
	TOURGETORDERS, TOURGUIDELOGIN, TOURGUIDEDETAILS, TOURGUIDENEWORDER, CHECKMAXVIS,TOURGUIDEWAITINGLIST,
	UPDATEINFO_REQUEST,DELETEINFO, UPDATE_ORDER,TOURGUIDEWAITINGLIS, SENDMAIL, CHECK_IF_SUBSCRIBER;
	 
}
