package common;

public enum TypeOfMessage {
	REQUESTINFO, UPDATEINFO, LOGIN_REQUEST, LOGOUT, NEW_ORDER, GET_ORDER,TOURGETORDERS, TOURGUIDELOGIN, TOURGUIDEDETAILS, TOURGUIDENEWORDER, CHECKMAXVIS;
}
