package common;

public enum TypeOfMessageReturn {
	LOGIN_SUCCESSFUL,LOGIN_FAILED,NEWORDER_SUCCESS,NEWORDER_FAILED, RETURN_ORDER, RETURN_ORDER_FAILED,TOUR_DETAILS, TOUR_MYORDERS,
	UPDATE_SUCCESS, UPDATE_FAILED, DELETE_ORDER_FAILED, DELETE_ORDER_SUCCESS, REQUESTINFO_SUCCESS,TOUR_MAXVISCHECK,
	UPDATEINFO_SUCCESS,UPDATEINFO_FAILED,REQUESTINFO_FAILED,LOGIN_FAILED_CONNECTED;
}
