package common;

public enum TypeOfMessageReturn {
	LOGIN_SUCCESSFUL,LOGIN_FAILED,NEWORDER_SUCCESS,NEWORDER_FAILED, RETURN_ORDER, RETURN_ORDER_FAILED,TOUR_DETAILS, TOUR_MYORDERS,
	UPDATE_SUCCESS, UPDATE_FAILED, REQUESTINFO_SUCCESS,TOUR_MAXVISCHECK, SUB_NEW_ORDER_SUCCESS,
	UPDATEINFO_SUCCESS,UPDATEINFO_FAILED,REQUESTINFO_FAILED, IS_SUBSCRIBER, IS_REGULAR, IS_GUIDE, SUB_NEW_ORDER_FAILED,
	HISTORY_ORDERS,PARK_STATUS, PARKENTERRETURNORDER, PARK_DISCOUNT,NEW_ORDERMAXVISCHECK,LOGIN_FAILED_CONNECTED,PARK_EXITSTATUS, APPROVED_RETURN;
}
